name: shark_habitat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # Core scientific computing
  - numpy=1.24.*
  - pandas=2.0.*
  - scipy=1.11.*

  # Geospatial data handling
  - xarray=2023.*
  - netcdf4=1.6.*
  - rasterio=1.3.*
  - rioxarray=0.15.*
  - geopandas=0.14.*
  - shapely=2.0.*
  - fiona=1.9.*
  - pyproj=3.6.*

  # Visualization
  - matplotlib=3.7.*
  - cartopy=0.22.*
  - seaborn=0.12.*

  # Jupyter environment
  - jupyterlab=4.0.*
  - ipykernel=6.25.*
  - notebook=7.0.*

  # Additional utilities
  - tqdm=4.66.*
  - pyyaml=6.0.*
  - requests=2.31.*

  # Pip-installable packages
  - pip=23.*
  - pip:
    # NASA data access
    - earthaccess==0.9.*
    - erddapy==2.2.*
    - podaac-data-subscriber==1.14.*

    # Copernicus Marine
    - copernicusmarine==1.0.*

    # Biodiversity databases
    - pygbif==0.6.*
    - pyobis==1.5.*

    # Global Fishing Watch
    - gfw-api-python-client==0.1.*

    # Bathymetry
    - pygmt==0.10.*

    # Additional spatial tools
    - scikit-learn==1.3.*
    - scikit-image==0.22.*
